In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv(r"kc_house_data.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [2]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
# remove the column

df.drop('id',axis=1,inplace=True)

In [4]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [5]:
df.dtypes

date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [6]:
df['date'].head(1)

0    20141013T000000
Name: date, dtype: object

In [7]:
df['date']=pd.to_datetime(df['date'].str.slice(0,8))

df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [8]:
df['sale_year']=df['date'].dt.year
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_year
0,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014
1,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014
2,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,2015
3,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2014
4,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2015

In [9]:
df['house_age']=df['sale_year']-df['yr_built']

df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_year,house_age
0,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,3,...,0,1955,0,98178,47.5112,-122.257,1340,5650,2014,59
1,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,3,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014,63
2,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,3,...,0,1933,0,98028,47.7379,-122.233,2720,8062,2015,82
3,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,5,...,910,1965,0,98136,47.5208,-122.393,1360,5000,2014,49
4,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,3,...,0,1987,0,98074,47.6168,-122.045,1800,7503,2015,28

In [10]:
df['is_renovated']=df['yr_renovated'].apply(lambda x : 1 if x>0 else 0)
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_year,house_age,is_renovated
0,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,3,...,1955,0,98178,47.5112,-122.257,1340,5650,2014,59,0
1,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,3,...,1951,1991,98125,47.7210,-122.319,1690,7639,2014,63,1
2,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,3,...,1933,0,98028,47.7379,-122.233,2720,8062,2015,82,0
3,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,5,...,1965,0,98136,47.5208,-122.393,1360,5000,2014,49,0
4,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,3,...,1987,0,98074,47.6168,-122.045,1800,7503,2015,28,0

In [11]:
df['bathrooms'].unique()

array([1.  , 2.25, 3.  , 2.  , 4.5 , 1.5 , 2.5 , 1.75, 2.75, 3.25, 4.  ,
       3.5 , 0.75, 4.75, 5.  , 4.25, 3.75, 0.  , 1.25, 5.25, 6.  , 0.5 ,
       5.5 , 6.75, 5.75, 8.  , 7.5 , 7.75, 6.25, 6.5 ])

In [12]:
df['bedrooms'].nunique()

13

In [13]:
df['floors'].unique()

array([1. , 2. , 1.5, 3. , 2.5, 3.5])

In [14]:
df['waterfront'].unique()

array([0, 1])

In [15]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'sale_year', 'house_age',
       'is_renovated'],
      dtype='object')

In [16]:
col_to_drop=['date','yr_built','zipcode','sale_year','yr_renovated']
df.drop(columns=col_to_drop,inplace=True)
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,is_renovated
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,47.5112,-122.257,1340,5650,59,0
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,47.7210,-122.319,1690,7639,63,1
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,47.7379,-122.233,2720,8062,82,0
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,47.5208,-122.393,1360,5000,49,0
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,47.6168,-122.045,1800,7503,28,0

In [17]:
df.duplicated().sum()

np.int64(5)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'lat', 'long', 'sqft_living15', 'sqft_lot15',
       'house_age', 'is_renovated'],
      dtype='object')

In [20]:
df.drop(columns='sqft_above',axis=1,inplace=True)

In [21]:
X=df.drop('price',axis=1)
y=df['price']

In [22]:
#pip install scikit_learn

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y ,test_size=0.2,random_state=42)

In [24]:
X_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,is_renovated
16968,3,1.50,1020,9072,1.0,0,0,3,7,100,47.6950,-122.301,1620,7930,84,0
6250,2,1.50,1620,1444,2.0,0,0,3,9,540,47.5892,-122.309,1660,1642,7,0
13664,3,2.50,2370,7916,2.0,0,0,3,9,0,47.5280,-122.171,2500,8221,25,0
7243,4,3.00,2800,7198,2.0,0,0,3,8,0,47.3538,-122.013,3610,7845,12,0
17290,4,2.50,2270,11500,1.0,0,0,3,8,730,47.7089,-122.241,2020,10918,47,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11966,4,2.00,2100,4500,1.0,0,0,5,7,1040,47.6699,-122.317,1920,3900,90,0
21580,3,3.00,2780,6000,2.0,0,0,3,9,0,47.5184,-121.886,2850,6000,1,0
5392,4,1.75,1310,9690,1.0,0,0,4,7,0,47.7559,-122.226,2280,9618,47,0
860,1,0.75,380,15000,1.0,0,0,3,5,0,47.4810,-122.323,1170,15000,51,0
15797,4,2.50,2550,7500,1.0,0,0,3,8,800,47.3165,-122.386,2260,8800,38,0

In [25]:
X_test.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_basement', 'lat',
       'long', 'sqft_living15', 'sqft_lot15', 'house_age', 'is_renovated'],
      dtype='object')

In [26]:
X_test.shape

(4322, 16)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [28]:
from sklearn.linear_model import LinearRegression
Model=LinearRegression()
Model.fit(X_train_scaled,y_train)
reg_pred=Model.predict(X_test_scaled)

train_score=Model.score(X_train_scaled,y_train)
test_score=Model.score(X_test_scaled,y_test)
gap=train_score-test_score

print("Train r2",train_score)
print("Test r2",test_score)
print("Gap",gap)

Train r2 0.6918839062930129
Test r2 0.7043799125413541
Gap -0.01249600624834124

In [29]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score,mean_absolute_percentage_error

mae=mean_absolute_error(y_test,reg_pred)
mse=mean_squared_error(y_test,reg_pred)
rmse=root_mean_squared_error(y_test,reg_pred)
r2=r2_score(y_test,reg_pred)
mape=mean_absolute_percentage_error(y_test,reg_pred)

print("mean_absolute_error",mae)
print("mean_squared_error",mse)
print("root mean_squared_error",rmse)
print("r2 score",r2)
print("mean_absolute_percentage_error",mape)

mean_absolute_error 126877.84487434528
mean_squared_error 43494897787.31509
root mean_squared_error 208554.30416875862
r2 score 0.7043799125413541
mean_absolute_percentage_error 0.24459901033826936

In [30]:
from sklearn.linear_model import Ridge

ridge=Ridge(alpha=10)
ridge.fit(X_train_scaled,y_train)
ridge_pred=ridge.predict(X_test_scaled)

train_score=ridge.score(X_train_scaled,y_train)
test_score=ridge.score(X_test_scaled,y_test)
gap=train_score-test_score

print("Train r2",train_score)
print("Test r2",test_score)
print("Gap",gap)

Train r2 0.69188353060315
Test r2 0.7043750032435747
Gap -0.012491472640424717

In [31]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score,mean_absolute_percentage_error

mae=mean_absolute_error(y_test,ridge_pred)
mse=mean_squared_error(y_test,ridge_pred)
rmse=root_mean_squared_error(y_test,ridge_pred)
r2=r2_score(y_test,ridge_pred)
mape=mean_absolute_percentage_error(y_test,ridge_pred)

print("mean_absolute_error",mae)
print("mean_squared_error",mse)
print("root mean_squared_error",rmse)
print("r2 score",r2)
print("mean_absolute_percentage_error",mape)

mean_absolute_error 126843.41953203017
mean_squared_error 43495620097.51723
root mean_squared_error 208556.03586930115
r2 score 0.7043750032435747
mean_absolute_percentage_error 0.24450382295503084

In [32]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

rf.fit(X_train,y_train)
rf_pred=rf.predict(X_test)

train_score=rf.score(X_train,y_train)
test_score=rf.score(X_test,y_test)
gap=train_score-test_score

print("Train r2",train_score)
print("Test r2",test_score)
print("Gap",gap)

Train r2 0.9332408519254234
Test r2 0.8762219848860979
Gap 0.05701886703932546

In [33]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score,mean_absolute_percentage_error

mae=mean_absolute_error(y_test,rf_pred)
mse=mean_squared_error(y_test,rf_pred)
rmse=root_mean_squared_error(y_test,rf_pred)
r2=r2_score(y_test,rf_pred)
mape=mean_absolute_percentage_error(y_test,rf_pred)

print("mean_absolute_error",mae)
print("mean_squared_error",mse)
print("root mean_squared_error",rmse)
print("r2 score",r2)
print("mean_absolute_percentage_error",mape)

mean_absolute_error 72899.02349719351
mean_squared_error 18211590971.297028
root mean_squared_error 134950.32779247712
r2 score 0.8762219848860979
mean_absolute_percentage_error 0.13049568996209898

In [34]:
#pip install xgboost

In [35]:
#pip install XGBooster
from xgboost import XGBRegressor
xgb=XGBRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    colsample_bytree=0.8,
    subsample=0.8,
    n_jobs=-1,
    random_state=42
)
xgb.fit(X_train,y_train)
xgb_pred=xgb.predict(X_test)


train_score=xgb.score(X_train,y_train)
test_score=xgb.score(X_test,y_test)
gap=train_score-test_score

print("Train r2",train_score)
print("Test r2",test_score)
print("Gap",gap)

Train r2 0.9851148881367819
Test r2 0.9047211139065247
Gap 0.08039377423025729

In [36]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score,mean_absolute_percentage_error

mae=mean_absolute_error(y_test,xgb_pred)
mse=mean_squared_error(y_test,xgb_pred)
rmse=root_mean_squared_error(y_test,xgb_pred)
r2=r2_score(y_test,xgb_pred)
mape=mean_absolute_percentage_error(y_test,xgb_pred)

print("mean_absolute_error",mae)
print("mean_squared_error",mse)
print("root mean_squared_error",rmse)
print("r2 score",r2)
print("mean_absolute_percentage_error",mape)

mean_absolute_error 65104.528408433594
mean_squared_error 14018483816.681332
root mean_squared_error 118399.67827946717
r2 score 0.9047211139065247
mean_absolute_percentage_error 0.11847670270046816

In [39]:
#save model
#pip install pickle

import pickle

with open("house_price_model.pkl" , "wb") as f:
    pickle.dump(xgb , f)